firstName: Joe
middleInitial: A
lastName: Bloggs
ssn: 012-34-5678
occupation: Programmer
phone: 0015551212
email: joe.bloggs@domain.com
address:
  street: 1 Anywhere Road
  county: Dublin
  city: Dublin
  postCode: D1
  countryCode: IE
  country: Ireland
employer:
  name: Acme Corp.
  usaAddress: 16 Acme Boulevard, Suite 400, Phoenix, AZ 12345
  foreignAddress: 1st Floor Acme Building, Dublin, D1, Ireland
financial:
  endOfTaxYear: 12/31/2023
  # Single | Married filing jointly | Married filing separately |
  # Head of household | Qualifying widow(er)
  filingStatus: Married filing separately
  # Income from wages.
  # IE: This value is found on ros.ie "Review your tax", and then go to
  #   "Employment Detail Summary" and look for "Pay for Income Tax".
  income: 100000.00
  # Tax you paid on wages in your own country.
  # IE: Go to ros.ie.  Generate an "Employment Detail Summary" in
  #   "Pay for Income Tax" and add together "Income tax paid" and "USC paid".
  incomeTax: 35000.00
  # All currency values reported here are in the currency of your country of
  # residence, but the IRS forms require values to be in USD, so you need an
  # exchange rate to convert from your country income to USD. The
  # `irs-form-filler` will convert the values for you.
  averageExchangeRate:	0.924
  averageExchangeRateSource: 'https://www.irs.gov/individuals/international-taxpayers/yearly-average-currency-exchange-rates'
  # Except 8938, which needs the treasury exchange rate, end of year, December
  # https://www.irsstreamlinedprocedures.com/fbar-department-of-treasury-exchange-rates-2020-2
  treasuryExchangeRate: 0.905
  # 1040 Schedule B and FBAR required
  countriesWithBankAccounts: Ireland
  haveVirtualCurrency: no
carryover:
  # Carryover is for the last 10 tax years
  general:
    # To update for last year, open last year's form `f1116.pdf`:
    # * Find line 8 and enter that value in `foreign-taxes` (total from Part II)
    # * Find line 24  and enter in `utilized` (the Part III "smaller of" value)
    2018:
      foreign-taxes: 28000
      utilized: 19000
  alternative-minimum-tax:
    # To update for last year, open last year's form `f1116amt.pdf`:
    # * Find line 8 and enter that value in `foreign-taxes` (total from Part II)
    # * Find line 24  and enter in `utilized` (the Part III "smaller of" value)
    2018:
      foreign-taxes: 28000
      utilized: 19000
# List all of your foreign accounts for f8938 and the separate FBAR.
# tip: The FBAR file via PDF never works, so use their online version.
accounts:
  - account: '12345-678'
    type: deposit
    name: Allied Irish Bank
    address: 37 O'Connell Street
    city: Dublin, Dublin 1, IRELAND
    currency: Euro
    value: 12345.67
    opened: false
    closed: false
    joint: false
    tax: false

  - account: '12345-679'
    type: custodial
    name: Irish Life
    address: 37 O'Connell Street
    city: Dublin, Dublin 1, IRELAND
    currency: Euro
    value: 10000.00
    opened: false
    closed: false
    joint: false
    tax: false
